version: '3.4'

services:
  wf-core-sample:
    image: ${DOCKER_REGISTRY-}wfcoresample
    build:
      context: .
      dockerfile: Dockerfile

  elastic:
    image: elasticsearch:6.5.4
    expose:
      - 9200    

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    expose: 
      - 27017